name: Daily Stats Update

on:
  workflow_dispatch:  # Manual trigger
  schedule:
    - cron: '0 8 * * *'  # Run daily at 8:00 UTC

jobs:
  update-stats:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests firebase-admin
          
      - name: Update playerlist with pre-acquisition stats
        env:
          FIREBASE_SERVICE_ACCOUNT_JSON: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_JSON }}
        run: |
          echo "Updating playerlist with pre-acquisition stats..."
          python scripts/update_playerlist.py
          
      - name: Run fetch stats script
        run: |
          echo "Fetching current playoff stats..."
          python scripts/fetch_stats.py
        
      - name: Run calculate standings script
        run: |
          echo "Calculating standings..."
          python scripts/calculate_standings.py
        
      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions@github.com'
          git add data/
          git commit -m "Update stats for $(date +'%Y%m%d')" || echo "No changes to commit"
          git pull --rebase origin master || echo "No remote changes to pull"
          git push