name: Generate Initial Playerlist

on:
  workflow_dispatch:  # Allow manual triggering

jobs:
  generate-playerlist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install firebase-admin
          
      - name: Run playerlist script
        env:
          FIREBASE_SERVICE_ACCOUNT_JSON: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_JSON }}
        run: |
          python scripts/playerlist_initial_population.py
          
      - name: Commit and push changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add data/playerlist.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "Generate initial playerlist.json" && git push)