name: Update NHL Player Database

on:
  workflow_dispatch:  # Manual trigger
  schedule:
    - cron: '0 0 1 * *'  # Run monthly on the 1st day of the month

jobs:
  update-player-database:
    runs-on: ubuntu-latest
   
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
       
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
         
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
          pip install firebase-admin
          pip install urllib3
         
      - name: Run player database script
        run: python scripts/get_all_players.py
       
      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions@github.com'
          git add data/nhl_players.json data/nhl_playoff_players.json
          git commit -m "Update NHL player database" || echo "No changes to commit"
          git push